<a href="https://colab.research.google.com/github/comp-lin-alg/CLA_colab/blob/main/GMRES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import *; import scipy.linalg as sl; import scipy.sparse.linalg as sspl

In [2]:
n = 50; s = 2.1

In [3]:
A0 = diag(s*ones(n)) - diag(ones(n-1), k=-1) - diag(ones(n-1), k =1); A0

array([[ 2.1, -1. ,  0. , ...,  0. ,  0. ,  0. ],
       [-1. ,  2.1, -1. , ...,  0. ,  0. ,  0. ],
       [ 0. , -1. ,  2.1, ...,  0. ,  0. ,  0. ],
       ...,
       [ 0. ,  0. ,  0. , ...,  2.1, -1. ,  0. ],
       [ 0. ,  0. ,  0. , ..., -1. ,  2.1, -1. ],
       [ 0. ,  0. ,  0. , ...,  0. , -1. ,  2.1]])

In [4]:
A = A0.copy(); A[0,-1] = -1; A[-1, 0] = -1; A

array([[ 2.1, -1. ,  0. , ...,  0. ,  0. , -1. ],
       [-1. ,  2.1, -1. , ...,  0. ,  0. ,  0. ],
       [ 0. , -1. ,  2.1, ...,  0. ,  0. ,  0. ],
       ...,
       [ 0. ,  0. ,  0. , ...,  2.1, -1. ,  0. ],
       [ 0. ,  0. ,  0. , ..., -1. ,  2.1, -1. ],
       [-1. ,  0. ,  0. , ...,  0. , -1. ,  2.1]])

In [5]:
P, L, U = sl.lu(A0); P

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [6]:
L

array([[ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.47619048,  1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        , -0.61583578,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ..., -0.72984379,
         1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.72984379,  1.        ]])

In [7]:
U

array([[ 2.1       , -1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.62380952, -1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.48416422, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  1.37015621,
        -1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.37015621, -1.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  1.37015621]])

In [8]:
def matvec(x):
  return s*x - roll(x,1) - roll(x,-1)

In [9]:
Amat = sspl.LinearOperator((n,n), matvec=matvec)

In [10]:
a = random.randn(n); a

array([-1.92896389e+00,  1.08560043e-03,  8.22148647e-01,  1.02171986e-01,
        4.16604152e-01, -5.64515836e-01,  1.95864618e-01, -7.77154338e-01,
       -1.92631812e+00, -7.08847066e-01, -1.52833223e-01,  5.05162264e-01,
        3.13045070e-01,  1.06348857e+00,  2.09588204e-01, -8.18623822e-02,
       -3.72031635e-01, -1.77956428e+00,  2.47880385e-01,  7.54942459e-01,
       -6.30640696e-03, -5.68113121e-01,  2.69374052e-01,  1.16152817e+00,
        5.05078338e-01, -8.71541927e-01,  1.13833290e-01,  5.83022373e-01,
        5.95434916e-01,  8.03880916e-01, -4.40477524e-01,  9.25444365e-01,
       -6.68120686e-01, -6.51735993e-01, -9.30701062e-01,  1.30710572e-01,
        7.40659996e-01,  1.55629190e+00, -4.71821550e-02,  1.58658399e-01,
        4.19263038e-02, -1.01270905e-01,  3.72883532e-01, -9.02857671e-01,
        8.17871060e-01,  2.14399296e-01, -1.38805818e-01,  9.91450196e-02,
       -1.34417128e+00,  2.88465457e-03])

In [11]:
linalg.norm(A@a - Amat@a)

7.957674067932935e-16

In [12]:
def Pinv(x):
  y = sl.solve_triangular(L, x, lower=True)
  return sl.solve_triangular(U, y)

In [13]:
M = sspl.LinearOperator((n,n), matvec=Pinv)

In [14]:
b = A0@a

In [15]:
xs = M@b; linalg.norm(xs-a)

2.139508702626223e-15

In [16]:
M@Amat@a

array([-1.93106910e+00, -4.50699590e-04,  8.21027634e-01,  1.01354158e-01,
        4.16007725e-01, -5.64950503e-01,  1.95548244e-01, -7.77384056e-01,
       -1.92648415e+00, -7.08966019e-01, -1.52916992e-01,  5.05105303e-01,
        3.13009221e-01,  1.06347025e+00,  2.09585578e-01, -8.18495762e-02,
       -3.72002116e-01, -1.77951509e+00,  2.47954152e-01,  7.55048187e-01,
       -6.15814677e-03, -5.67907502e-01,  2.69657592e-01,  1.16191798e+00,
        5.05613409e-01, -8.70808093e-01,  1.14839270e-01,  5.84401098e-01,
        5.97324258e-01,  8.06469810e-01, -4.36930190e-01,  9.30304873e-01,
       -6.61460953e-01, -6.42611062e-01, -9.18198440e-01,  1.47841148e-01,
        7.64131583e-01,  1.58845165e+00, -3.11825253e-03,  2.19032838e-01,
        1.24648722e-01,  1.20717346e-02,  5.28180656e-01, -6.90076349e-01,
        1.10941471e+00,  6.13859643e-01,  4.08517259e-01,  8.49063135e-01,
       -3.16666313e-01,  1.41072696e+00])

In [17]:
def call(s):
  print(s)

In [18]:
x, info = sspl.gmres(Amat, a, tol=1.0e-10, callback=call, callback_type='pr_norm')

0.6085048204658695
0.38774546818457395
0.24267250669408708
0.1925782870219188
0.15912077716336587
0.11760402889082346
0.08790405955568434
0.06659690303141763
0.04937984294885966
0.02912308629609039
0.01703558170611859
0.011829537852091938
0.008530276825222774
0.005798812004809786
0.003985048670916809
0.0027712069871518447
0.0020844539386390805
0.0013057433392828007
0.0009483965500827302
0.0007558550296883783
0.0006635414472697927
0.0005213049703809643
0.0003694987884314716
0.0002745317692079269
0.00021540949902138596
0.00016899027338026403
0.0001237297788463431
9.055436621913258e-05
6.298213274872885e-05
4.7136594938891816e-05
2.8835142236257065e-05
2.179234502472378e-05
1.5664250487308116e-05
1.2208220270641371e-05
7.6213640336175665e-06
4.897391848944561e-06
3.2699193789341855e-06
2.244619107432298e-06
1.3803144215096524e-06
6.243896132650753e-07
3.645099147802251e-07
2.8085955351726874e-07
2.1841602574795574e-07
1.7730415869744987e-07
1.4224385595529142e-07
1.021466967326046e-07
7.0

In [19]:
x, info = sspl.gmres(Amat, a, tol=1.0e-10, callback=call, M=M, callback_type='pr_norm')

0.2699794754351277
0.19392535510122888
8.78204215092395e-16


In [20]:
e, _ = linalg.eig(A); e

array([0.1       , 0.1157706 , 0.16283368, 0.24044703, 0.34738664,
       0.48196601, 0.64206275, 0.82515202, 1.02834641, 1.24844142,
       1.48196601, 1.72523737, 1.97441896, 2.22558104, 2.47476263,
       2.71803399, 2.95155858, 3.17165359, 4.1       , 4.0842294 ,
       4.03716632, 3.95955297, 3.85261336, 3.71803399, 3.37484798,
       3.55793725, 4.0842294 , 4.03716632, 3.95955297, 3.85261336,
       3.71803399, 3.55793725, 3.37484798, 3.17165359, 2.95155858,
       2.71803399, 2.47476263, 2.22558104, 0.1157706 , 0.16283368,
       0.24044703, 0.34738664, 0.48196601, 0.64206275, 0.82515202,
       1.02834641, 1.24844142, 1.97441896, 1.72523737, 1.48196601])