<a href="https://colab.research.google.com/github/comp-lin-alg/CLA_colab/blob/main/L_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import *

In [2]:
set_printoptions(precision=6, suppress=True)

In [3]:
def ek(k,n):
  e = zeros(n,)
  e[k] = 1
  return e

In [4]:
e = ek(0,5)

In [5]:
col = random.randn(5); col

array([-0.475485, -0.138376,  0.561279,  0.447463, -0.479643])

In [6]:
l = -col.copy(); l[0] = 0; l /= col[0]

In [7]:
l

array([-0.      , -0.291022,  1.180434,  0.941068, -1.008746])

In [8]:
outer(l,e)

array([[-0.      , -0.      , -0.      , -0.      , -0.      ],
       [-0.291022, -0.      , -0.      , -0.      , -0.      ],
       [ 1.180434,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.941068,  0.      ,  0.      ,  0.      ,  0.      ],
       [-1.008746, -0.      , -0.      , -0.      , -0.      ]])

In [9]:
L0 = outer(l,e) + eye(5)

Checking that the inverse formula works.

In [10]:
L0

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.291022,  1.      ,  0.      ,  0.      ,  0.      ],
       [ 1.180434,  0.      ,  1.      ,  0.      ,  0.      ],
       [ 0.941068,  0.      ,  0.      ,  1.      ,  0.      ],
       [-1.008746,  0.      ,  0.      ,  0.      ,  1.      ]])

In [11]:
linalg.inv(L0)

array([[ 1.      ,  0.      ,  0.      ,  0.      , -0.      ],
       [ 0.291022,  1.      ,  0.      ,  0.      , -0.      ],
       [-1.180434,  0.      ,  1.      ,  0.      ,  0.      ],
       [-0.941068,  0.      ,  0.      ,  1.      ,  0.      ],
       [ 1.008746,  0.      , -0.      ,  0.      ,  1.      ]])

Checking that the cancellation formula works

In [12]:
L0@col

array([-0.475485,  0.      ,  0.      ,  0.      ,  0.      ])

In [13]:
col = random.randn(5); col = L0@col

In [14]:
l = -col.copy(); l[:2]=0; l /= col[1]; l

array([-0.      , -0.      , -1.318754,  0.176805,  0.471764])

In [15]:
e = ek(1,5)

In [16]:
L1 = outer(l,e) + eye(5)

Checking that product formula works.

In [17]:
L1

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  1.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      , -1.318754,  1.      ,  0.      ,  0.      ],
       [ 0.      ,  0.176805,  0.      ,  1.      ,  0.      ],
       [ 0.      ,  0.471764,  0.      ,  0.      ,  1.      ]])

In [18]:
linalg.inv(L1)

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.      ,  1.      , -0.      , -0.      , -0.      ],
       [ 0.      ,  1.318754,  1.      ,  0.      ,  0.      ],
       [ 0.      , -0.176805,  0.      ,  1.      ,  0.      ],
       [ 0.      , -0.471764,  0.      ,  0.      ,  1.      ]])

In [21]:
linalg.inv(L0)@linalg.inv(L1)

array([[ 1.      ,  0.      ,  0.      ,  0.      , -0.      ],
       [ 0.291022,  1.      ,  0.      ,  0.      , -0.      ],
       [-1.180434,  1.318754,  1.      ,  0.      ,  0.      ],
       [-0.941068, -0.176805,  0.      ,  1.      ,  0.      ],
       [ 1.008746, -0.471764, -0.      ,  0.      ,  1.      ]])

Checking that the product formula is special

In [19]:
linalg.inv(L1)@linalg.inv(L0)

array([[ 1.      ,  0.      ,  0.      ,  0.      , -0.      ],
       [ 0.291022,  1.      ,  0.      ,  0.      , -0.      ],
       [-0.796648,  1.318754,  1.      ,  0.      ,  0.      ],
       [-0.992522, -0.176805,  0.      ,  1.      ,  0.      ],
       [ 0.871452, -0.471764, -0.      ,  0.      ,  1.      ]])

Once more for emphasis!

In [22]:
col = random.randn(5); col = L1@L0@col

In [24]:
l = -col.copy(); l[:3]=0; l /= col[2]; l

array([ -0.      ,  -0.      ,  -0.      , -12.194598, -12.00237 ])

In [25]:
e = ek(2,5)

In [26]:
L2 = outer(l,e) + eye(5)

In [27]:
L2

array([[  1.      ,   0.      ,   0.      ,   0.      ,   0.      ],
       [  0.      ,   1.      ,   0.      ,   0.      ,   0.      ],
       [  0.      ,   0.      ,   1.      ,   0.      ,   0.      ],
       [  0.      ,   0.      , -12.194598,   1.      ,   0.      ],
       [  0.      ,   0.      , -12.00237 ,   0.      ,   1.      ]])

In [28]:
linalg.inv(L2)

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  1.      ,  0.      ,  0.      ,  0.      ],
       [-0.      , -0.      ,  1.      , -0.      , -0.      ],
       [-0.      , -0.      , 12.194598,  1.      , -0.      ],
       [ 0.      ,  0.      , 12.00237 ,  0.      ,  1.      ]])

In [29]:
linalg.inv(L0)@linalg.inv(L1)@linalg.inv(L2)

array([[ 1.      ,  0.      , -0.      , -0.      , -0.      ],
       [ 0.291022,  1.      , -0.      , -0.      , -0.      ],
       [-1.180434,  1.318754,  1.      , -0.      ,  0.      ],
       [-0.941068, -0.176805, 12.194598,  1.      ,  0.      ],
       [ 1.008746, -0.471764, 12.00237 ,  0.      ,  1.      ]])