<a href="https://colab.research.google.com/github/comp-lin-alg/CLA_colab/blob/main/perms_and_Ls.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import *; from scipy import linalg as slinalg

In [2]:
set_printoptions(precision=6, suppress=True)

In [3]:
p = random.permutation(10); p

array([7, 3, 9, 1, 6, 8, 4, 0, 2, 5])

In [4]:
pinv = empty_like(p); pinv[p] = arange(10, dtype=int); pinv

array([7, 3, 8, 1, 6, 9, 4, 0, 5, 2])

In [5]:
x = random.randn(10); x

array([-0.383601, -0.051311,  1.002392, -1.397828,  0.134009,  0.54183 ,
       -0.179363, -0.828772,  0.09754 , -0.272029])

(Px)_i = x_{p_i}

In [6]:
x[p]

array([-0.828772, -1.397828, -0.272029, -0.051311, -0.179363,  0.09754 ,
        0.134009, -0.383601,  1.002392,  0.54183 ])

In [7]:
I = eye(10, dtype=int); P = I[p,:]; P

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [8]:
linalg.norm(P@x - x[p], ord=inf)

0.0

In [9]:
A = random.randn(100, 100)

In [10]:
P, L, U = slinalg.lu(A)

In [11]:
linalg.norm(A-P@L@U, ord=inf)

6.187411694114076e-14

In [12]:
linalg.norm(U, ord=inf)/linalg.norm(A, ord=inf)

2.90990512785039

In [13]:
def get_L(k,n):
  e = zeros(n,)
  e[k] = 1
  l = zeros(n,)
  l[k+1:] = random.randn(*(l[k+1:].shape))
  return eye(n) - outer(l, e)

In [14]:
get_L(3,5)

array([[1.      , 0.      , 0.      , 0.      , 0.      ],
       [0.      , 1.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 1.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 1.      , 0.      ],
       [0.      , 0.      , 0.      , 0.295373, 1.      ]])

In [15]:
L1 = get_L(0,5); L1

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.766675,  1.      ,  0.      ,  0.      ,  0.      ],
       [-0.405006,  0.      ,  1.      ,  0.      ,  0.      ],
       [ 0.581654,  0.      ,  0.      ,  1.      ,  0.      ],
       [-0.113716,  0.      ,  0.      ,  0.      ,  1.      ]])

In [16]:
p1 = arange(5, dtype=int); p1[[0,3]] = p1[[3,0]]; p1

array([3, 1, 2, 0, 4])

In [17]:
L1[:, p1]

array([[ 0.      ,  0.      ,  0.      ,  1.      ,  0.      ],
       [ 0.      ,  1.      ,  0.      , -0.766675,  0.      ],
       [ 0.      ,  0.      ,  1.      , -0.405006,  0.      ],
       [ 1.      ,  0.      ,  0.      ,  0.581654,  0.      ],
       [ 0.      ,  0.      ,  0.      , -0.113716,  1.      ]])

In [18]:
x = random.randn(5)

In [19]:
L1[:, p1]@x

array([-0.965324,  1.122928,  1.921278, -0.435031,  0.239732])

In [20]:
L1@x[p1]

array([-0.965324,  1.122928,  1.921278, -0.435031,  0.239732])

In [21]:
L2 = get_L(1,5); L2

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  1.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.514566,  1.      ,  0.      ,  0.      ],
       [ 0.      , -1.066338,  0.      ,  1.      ,  0.      ],
       [ 0.      ,  1.613909,  0.      ,  0.      ,  1.      ]])

In [22]:
p2 = arange(5, dtype=int); p2[[1,4]] = p2[[4,1]]; p2

array([0, 4, 2, 3, 1])

In [23]:
p2[p2]

array([0, 1, 2, 3, 4])

In [24]:
L1p = zeros_like(L1); L1p[p2, :] = L1[:, :]; L1p

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.113716,  0.      ,  0.      ,  0.      ,  1.      ],
       [-0.405006,  0.      ,  1.      ,  0.      ,  0.      ],
       [ 0.581654,  0.      ,  0.      ,  1.      ,  0.      ],
       [-0.766675,  1.      ,  0.      ,  0.      ,  0.      ]])

In [25]:
L1p@x

array([ 0.126454,  0.115579,  1.479102, -0.891772,  0.285889])

In [26]:
(L1@x)[p2]

array([ 0.126454,  0.115579,  1.479102, -0.891772,  0.285889])

In [27]:
L1p = L1[:, p2]; L1p

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.766675,  0.      ,  0.      ,  0.      ,  1.      ],
       [-0.405006,  0.      ,  1.      ,  0.      ,  0.      ],
       [ 0.581654,  0.      ,  0.      ,  1.      ,  0.      ],
       [-0.113716,  1.      ,  0.      ,  0.      ,  0.      ]])

In [28]:
L1p@x

array([ 0.126454,  0.03301 ,  1.479102, -0.891772,  0.368459])

In [29]:
L1@(x[p2])

array([ 0.126454,  0.03301 ,  1.479102, -0.891772,  0.368459])

In [31]:
L1pp = zeros_like(L1p); L1pp[p2, :] = L1p[:, :]; L1pp

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.113716,  1.      ,  0.      ,  0.      ,  0.      ],
       [-0.405006,  0.      ,  1.      ,  0.      ,  0.      ],
       [ 0.581654,  0.      ,  0.      ,  1.      ,  0.      ],
       [-0.766675,  0.      ,  0.      ,  0.      ,  1.      ]])

In [39]:
L1

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.766675,  1.      ,  0.      ,  0.      ,  0.      ],
       [-0.405006,  0.      ,  1.      ,  0.      ,  0.      ],
       [ 0.581654,  0.      ,  0.      ,  1.      ,  0.      ],
       [-0.113716,  0.      ,  0.      ,  0.      ,  1.      ]])

In [41]:
L2p = L2[:, p2]; L2pp = zeros_like(L2); L2pp[p2, :] = L2p; L2pp

array([[ 1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  1.      ,  0.      ,  0.      ,  1.613909],
       [ 0.      ,  0.      ,  1.      ,  0.      ,  0.514566],
       [ 0.      ,  0.      ,  0.      ,  1.      , -1.066338],
       [ 0.      ,  0.      ,  0.      ,  0.      ,  1.      ]])