In [1]:
from numpy import *

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
A = random.randn(5,3)

In [4]:
A

array([[-0.12653895,  1.23013544,  0.68511823],
       [-0.26626038,  0.30266063, -0.66491454],
       [-0.88539249,  0.82094151, -0.15883443],
       [-0.73472224,  0.38996509, -0.93263001],
       [ 0.25386932,  1.48683602,  0.57940308]])

In [5]:
Q, R = linalg.qr(A)

In [6]:
Q

array([[-0.10418724,  0.56877966, -0.37299957],
       [-0.21922842,  0.07150018,  0.62285594],
       [-0.72899767,  0.14643825, -0.42412232],
       [-0.60494166, -0.02187995,  0.45235909],
       [ 0.2090261 ,  0.80588741,  0.29734375]])

In [7]:
R

array([[ 1.21453405, -0.71809927,  0.87547462],
       [ 0.        ,  2.03122357,  0.80621992],
       [ 0.        ,  0.        , -0.85193133]])

In [8]:
Q2, R2 = linalg.qr(A, mode="complete")

In [9]:
Q2

array([[-0.10418724,  0.56877966, -0.37299957, -0.41209205, -0.59723209],
       [-0.21922842,  0.07150018,  0.62285594, -0.71689307,  0.21199395],
       [-0.72899767,  0.14643825, -0.42412232,  0.02177937,  0.51649216],
       [-0.60494166, -0.02187995,  0.45235909,  0.42966394, -0.49429446],
       [ 0.2090261 ,  0.80588741,  0.29734375,  0.36215885,  0.29543397]])

In [10]:
R2

array([[ 1.21453405, -0.71809927,  0.87547462],
       [ 0.        ,  2.03122357,  0.80621992],
       [ 0.        ,  0.        , -0.85193133],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

Note that to apply Q (or Q2), we just need the vs (see notes).

Now to apply QR to least squares problems.

In [11]:
x = random.randn(3)

In [12]:
x

array([-0.20631076, -0.04614831,  0.05264398])

In [13]:
b = A@x

In [14]:
b

array([ 0.00540503,  0.00596136,  0.13641926,  0.08448752, -0.09048885])

In [15]:
linalg.norm(A@x-b)

0.0

In [16]:
linalg.norm(R@x-Q.T@b)

1.0500451862475693e-16

In [17]:
b += 0.1*random.randn(b.size)

In [18]:
b

array([ 0.06324988,  0.02167215,  0.19721729,  0.06485657, -0.36716841])

In [19]:
x = linalg.solve(R, Q.T@b)

In [20]:
linalg.norm(A@x-b)

0.15951199127872687

In [21]:
x

array([-0.48510019, -0.19454861,  0.20374245])

In [22]:
linalg.norm(R@x-Q.T@b)

0.0

In [34]:
bstar = Q@Q.T@b
linalg.norm(A@x-bstar)

1.8670653977139892e-16

In [24]:
A1 = hstack((A, b.reshape((5,1))))

In [25]:
A1

array([[-0.12653895,  1.23013544,  0.68511823,  0.06324988],
       [-0.26626038,  0.30266063, -0.66491454,  0.02167215],
       [-0.88539249,  0.82094151, -0.15883443,  0.19721729],
       [-0.73472224,  0.38996509, -0.93263001,  0.06485657],
       [ 0.25386932,  1.48683602,  0.57940308, -0.36716841]])

In [30]:
Q3, R3 = linalg.qr(A1)

In [31]:
R3

array([[ 1.21453405, -0.71809927,  0.87547462, -0.27109415],
       [ 0.        ,  2.03122357,  0.80621992, -0.2309105 ],
       [ 0.        ,  0.        , -0.85193133, -0.17357457],
       [ 0.        ,  0.        ,  0.        ,  0.15951199]])

In [32]:
Q.T@b

array([-0.27109415, -0.2309105 , -0.17357457])